# automatically generated by the FlatBuffers compiler, do not modify

# namespace: clipper

import flatbuffers

class ByteVec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsByteVec(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ByteVec()
        x.Init(buf, n + offset)
        return x

    # ByteVec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ByteVec
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ByteVec
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ByteVecStart(builder): builder.StartObject(1)
def ByteVecAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def ByteVecStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def ByteVecEnd(builder): return builder.EndObject()
