# automatically generated by the FlatBuffers compiler, do not modify

# namespace: clipper

import flatbuffers

class DoubleVec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDoubleVec(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DoubleVec()
        x.Init(buf, n + offset)
        return x

    # DoubleVec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DoubleVec
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # DoubleVec
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def DoubleVecStart(builder): builder.StartObject(1)
def DoubleVecAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def DoubleVecStartDataVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def DoubleVecEnd(builder): return builder.EndObject()
