# automatically generated by the FlatBuffers compiler, do not modify

# namespace: clipper

import flatbuffers

class IntVec(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIntVec(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IntVec()
        x.Init(buf, n + offset)
        return x

    # IntVec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntVec
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IntVec
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def IntVecStart(builder): builder.StartObject(1)
def IntVecAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def IntVecStartDataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IntVecEnd(builder): return builder.EndObject()
