// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP rclipper_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP serve_data_frame_model(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP serve_integer_vector_model(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP serve_numeric_vector_model(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP serve_raw_vector_model(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"rclipper_rcpp_hello_world", (DL_FUNC) &rclipper_rcpp_hello_world, 0},
    {"serve_data_frame_model",     (DL_FUNC) &serve_data_frame_model,     6},
    {"serve_integer_vector_model", (DL_FUNC) &serve_integer_vector_model, 6},
    {"serve_numeric_vector_model", (DL_FUNC) &serve_numeric_vector_model, 6},
    {"serve_raw_vector_model",     (DL_FUNC) &serve_raw_vector_model,     6},
    {NULL, NULL, 0}
};

RcppExport void R_init_rclipper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
