FROM tensorflow/tensorflow:1.12.0-gpu-py3

#docker 1
RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN apt-get install libsm6 libxext6 libxrender-dev -y
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install grpcio
RUN pip3 install protobuf

#docker 2
RUN pip3 install scipy
RUN pip3 install imutils
RUN pip3 install cMake
RUN pip3 install dlib

#docker 3
RUN pip3 install scikit-image
RUN pip3 install Cython
RUN pip3 install pycocotools
RUN pip3 install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
RUN pip3 install keras
RUN pip3 install imgaug
#docker 4 none
#add
ADD container1 /container/container1
ADD container2 /container/container2
ADD container3 /container/container3
ADD container4 /container/container4
ADD main.py /container/
ADD part1 /container/part1

CMD ["python3","/container/main.py"]

# docker build -f ./FatigueDetections/Dockerfile_main -t detection:main .
# docker run --runtime=nvidia -p 10000:10000 -it detection:main
# docker run --runtime=nvidia -d -p 10000:10000 -it detection:main


