# automatically generated by the FlatBuffers compiler, do not modify

# namespace: clipper

import flatbuffers

class FeedbackRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFeedbackRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeedbackRequest()
        x.Init(buf, n + offset)
        return x

    # FeedbackRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FeedbackRequestStart(builder): builder.StartObject(0)
def FeedbackRequestEnd(builder): return builder.EndObject()
