# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PATH/rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PATH/rpc.proto',
  package='clipper',
  syntax='proto2',
  serialized_pb=_b('\n\x0ePATH/rpc.proto\x12\x07\x63lipper\"\x1b\n\x0bRequestData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x87\x01\n\x07Request\x12*\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x14.clipper.RequestType\x12$\n\tdata_type\x18\x02 \x01(\x0e\x32\x11.clipper.DataType\x12*\n\x0crequest_data\x18\x03 \x03(\x0b\x32\x14.clipper.RequestData*\x1a\n\x0bRequestType\x12\x0b\n\x07PREDICT\x10\x00*.\n\x08\x44\x61taType\x12\x08\n\x04INTS\x10\x00\x12\x0b\n\x07\x44OUBLES\x10\x01\x12\x0b\n\x07STRINGS\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='clipper.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREDICT', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=194,
  serialized_end=220,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='clipper.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLES', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRINGS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=222,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
PREDICT = 0
INTS = 0
DOUBLES = 1
STRINGS = 2



_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='clipper.RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='clipper.RequestData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=54,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='clipper.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='clipper.Request.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='clipper.Request.data_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_data', full_name='clipper.Request.request_data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=192,
)

_REQUEST.fields_by_name['request_type'].enum_type = _REQUESTTYPE
_REQUEST.fields_by_name['data_type'].enum_type = _DATATYPE
_REQUEST.fields_by_name['request_data'].message_type = _REQUESTDATA
DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDATA,
  __module__ = 'PATH.rpc_pb2'
  # @@protoc_insertion_point(class_scope:clipper.RequestData)
  ))
_sym_db.RegisterMessage(RequestData)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'PATH.rpc_pb2'
  # @@protoc_insertion_point(class_scope:clipper.Request)
  ))
_sym_db.RegisterMessage(Request)


# @@protoc_insertion_point(module_scope)
