version: '2'

services:
  redis:
    image: redis:alpine
    cpuset: "0"
    ports:
      - "6379:6379"

  query_frontend:
    image: "clipper/query_frontend"
    depends_on:
      - redis
      - mgmt_frontend
    ports:
      - "7000:7000" # RPC Service port
      - "1337:1337" # REST port
    command: 
      - "--redis_ip=redis"
      - "--redis_port=6379"

  mgmt_frontend:
    image: "clipper/management_frontend"
    depends_on:
      - redis
    ports:
      - "1338:1338" # REST port
    command: 
      - "--redis_ip=redis"
      - "--redis_port=6379"
