version: '2'

services:
  redis:
    image: redis:alpine
    cpuset: "0"
    # This doesn't need to be exposed, but it allows one
    # to connect connect to redis via redis-cli for inspection
    expose:
      - "6379"

  query_frontend:
    image: clipper/query_frontend
    depends_on:
      - redis
      - mgmt_frontend
    expose:
      - "7000" # RPC Service port
      - "1337" # REST port
    command: 
      - "--redis_ip=redis"
      - "--redis_port=6379"

  mgmt_frontend:
    image: clipper/management_frontend
    depends_on:
      - redis
    expose:
      - "1338" # REST port
    command: 
      - "--redis_ip=redis"
      - "--redis_port=6379"

