{
 "title": "Word Vectorizer & Logistic Regression",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Decision Probabilty",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "custom_choice_probability_sum/custom_char_count_count"
    }
   ]
  },
  {
   "title": "Number of Spam Classified",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "custom_spam_option_counter" }
   ]
  },
  {
   "title": "Number of Ham Classified",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "custom_ham_option_counter" }
   ]
  },
  {
   "title": "Char & Word Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(custom_char_count_sum[5m])/rate(custom_char_count_count[5m])"
    },
    {
     "expr": "rate(custom_word_count_sum[5m])/rate(custom_word_count_count[5m])"
    }
   ]
  },
  {
   "title": "Vectorizer & LR 90th Percentile (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(custom_vectorization_time_ms_bucket[10m]))"
    },
    {
     "expr": "histogram_quantile(0.9, rate(custom_lr_time_ms_bucket[10m]))"
    }
   ]
  }
 ]
}