# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy.proto',
  package='lmjwtest',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bproxy.proto\x12\x08lmjwtest\"/\n\x05input\x12\x11\n\tinputType\x18\x01 \x01(\t\x12\x13\n\x0binputStream\x18\x02 \x01(\t\"B\n\tmodelinfo\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\x11\n\tmodelPort\x18\x02 \x01(\t\x12\x0f\n\x07modelId\x18\x03 \x01(\t\"\x13\n\x03\x64\x61g\x12\x0c\n\x04\x64\x61g_\x18\x01 \x01(\t\"\x1a\n\x08response\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd7\x01\n\x0cProxyService\x12\x30\n\x07Predict\x12\x0f.lmjwtest.input\x1a\x12.lmjwtest.response\"\x00\x12/\n\x06Return\x12\x0f.lmjwtest.input\x1a\x12.lmjwtest.response\"\x00\x12\x35\n\x08SetModel\x12\x13.lmjwtest.modelinfo\x1a\x12.lmjwtest.response\"\x00\x12-\n\x06SetDAG\x12\r.lmjwtest.dag\x1a\x12.lmjwtest.response\"\x00\x62\x06proto3')
)




_INPUT = _descriptor.Descriptor(
  name='input',
  full_name='lmjwtest.input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputType', full_name='lmjwtest.input.inputType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputStream', full_name='lmjwtest.input.inputStream', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=72,
)


_MODELINFO = _descriptor.Descriptor(
  name='modelinfo',
  full_name='lmjwtest.modelinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelName', full_name='lmjwtest.modelinfo.modelName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modelPort', full_name='lmjwtest.modelinfo.modelPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modelId', full_name='lmjwtest.modelinfo.modelId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=140,
)


_DAG = _descriptor.Descriptor(
  name='dag',
  full_name='lmjwtest.dag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dag_', full_name='lmjwtest.dag.dag_', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=161,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='lmjwtest.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='lmjwtest.response.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['input'] = _INPUT
DESCRIPTOR.message_types_by_name['modelinfo'] = _MODELINFO
DESCRIPTOR.message_types_by_name['dag'] = _DAG
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

input = _reflection.GeneratedProtocolMessageType('input', (_message.Message,), dict(
  DESCRIPTOR = _INPUT,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:lmjwtest.input)
  ))
_sym_db.RegisterMessage(input)

modelinfo = _reflection.GeneratedProtocolMessageType('modelinfo', (_message.Message,), dict(
  DESCRIPTOR = _MODELINFO,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:lmjwtest.modelinfo)
  ))
_sym_db.RegisterMessage(modelinfo)

dag = _reflection.GeneratedProtocolMessageType('dag', (_message.Message,), dict(
  DESCRIPTOR = _DAG,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:lmjwtest.dag)
  ))
_sym_db.RegisterMessage(dag)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:lmjwtest.response)
  ))
_sym_db.RegisterMessage(response)



_PROXYSERVICE = _descriptor.ServiceDescriptor(
  name='ProxyService',
  full_name='lmjwtest.ProxyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=192,
  serialized_end=407,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='lmjwtest.ProxyService.Predict',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Return',
    full_name='lmjwtest.ProxyService.Return',
    index=1,
    containing_service=None,
    input_type=_INPUT,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetModel',
    full_name='lmjwtest.ProxyService.SetModel',
    index=2,
    containing_service=None,
    input_type=_MODELINFO,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetDAG',
    full_name='lmjwtest.ProxyService.SetDAG',
    index=3,
    containing_service=None,
    input_type=_DAG,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROXYSERVICE)

DESCRIPTOR.services_by_name['ProxyService'] = _PROXYSERVICE

# @@protoc_insertion_point(module_scope)
