apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: ""
    ai.clipper.name: redis
  name: redis
spec:
  type: NodePort
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    ai.clipper.name: redis
