apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: mgmt-frontend
  name: mgmt-frontend-at-{{ cluster_name }}
spec:
  type: {{ service_type }}
  ports:
  - name: "1338"
    port: 1338
    targetPort: 1338
  selector:
    ai.clipper.name: mgmt-frontend
    ai.clipper.container.label: {{ cluster_name }}
