apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: ""
    ai.clipper.name: metrics
  name: metrics
spec:
  type: NodePort
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    ai.clipper.name: metrics
