apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: metrics
  name: metrics-at-{{ cluster_name }}
spec:
  type: {{ service_type }}
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    ai.clipper.name: metrics
