apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: query-frontend
  name: {{ name }}-at-{{ cluster_name }}
spec:
  type: {{ service_type }}
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  selector:
    ai.clipper.name: query-frontend
    ai.clipper.query_frontend.id: "{{ id_label }}"
    ai.clipper.container.label: {{ cluster_name }}
