apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: query-frontend
  name: query-frontend-at-{{ cluster_name }}
spec:
  type: {{ service_type }}
  ports:
  - name: "1337"
    port: 1337
    targetPort: 1337
  selector:
    ai.clipper.name: query-frontend
    ai.clipper.container.label: {{ cluster_name }}
