apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: redis
  name: {{ deployment_name }} # Cluster name included
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ai.clipper.container.label: {{ cluster_name }}
        ai.clipper.name: redis
    spec:
      containers:
      - args:
        - redis-server
        - --port
        - "6379"
        image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
